#pragma config(Motor,  motorA,          carm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          marm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          plat,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          cspin,         tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//code to reorient

void U(int x)
{
	reorientX();
	reorientX();
	holdCube();
	turnDown(x);
	resetArm();
	reorientX();
	reorientX();
}

void L(int x){
	turnDown(1,0);
	reorientX();
	holdCube();
	turnDown(x,1);
	resetArm();
	reorientX();
	reorientX();
	reorientX();
	resetArm();
	turnDown(-x,0);

}
task main()
{

}
