#pragma config(Motor,  motorA,          carm,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          marm,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          plat,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          cspin,         tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int sp =40;
const int turnSpeed=100;
const int holdAngle=280;
const int noHoldAngle=310;

task main()
{
	int x=1;
	bool hold=1;

	int initEnc=nMotorEncoder[plat];

	if (x>0)
		motor[plat]=turnSpeed;
	else
		motor[plat]=-turnSpeed;

	if (hold)
		while (fabs(initEnc-nMotorEncoder[plat])<fabs(holdAngle*x));
	else
		while (fabs(initEnc-nMotorEncoder[plat])<fabs(noHoldAngle*x));

	motor[plat]=0;
	if (x>0)
		motor[plat]=-turnSpeed;
	else
		motor[plat]=turnSpeed;
	while (fabs(initEnc-nMotorEncoder[plat])>fabs(90*3*x));
	motor[plat]=0;
	int ang=nMotorEncoder[plat]/3;
	displayString(0,"%d",ang);
	wait1Msec(250);
}
