#pragma config(Motor,  motorA,          carm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          marm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          plat,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          cspin,         tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int sp=25;

task main()
{
	//sets the arm down to hold the cube
	if (nMotorEncoder[motorB]<-100){
		motor[marm]=sp;
		while (nMotorEncoder[motorB]<-165)
		{}
		motor[marm]=0;
	}
	else{
		motor[marm]=-sp
		while (nMotorEncoder[motorB]>-165)
		{}
		motor[marm]=0;
	}
}
