#pragma config(Motor,  motorA,          carm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          marm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          plat,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          cspin,         tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//code to reorient

void U(int funct)
{
	reorientX();
	reorientX();
	if(funct==0)
	turnDown(0,1);
	else
	turnDown(1,1);
	reorientX();
	reorientX();
}

void L(bool prime){
	turnDown(


}
task main()
{

}
