
#pragma config(Motor,  motorA,          carm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          marm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          plat,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          cspin,         tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int sp =40;
task main()
{

	motor[marm]=-sp;
	while(nMotorEncoder[motorB]>-260)
	{}
	motor[marm]=0;
	if (nMotorEncoder[motorB]>0){
		motor[marm]=-sp;
		while (nMotorEncoder[motorB]>0)
		{}
		motor[marm]=0;
	}
	else{
		motor[marm]=sp;
		while (nMotorEncoder[motorB]<0)
		{}
		motor[marm]=0;
	}

}
